services:
  # potatobot service - combines API and web interface

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    depends_on:
      - potatobot
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf

  potatobot:
    build:
      context: .
      dockerfile: chatbot/Dockerfile     
    volumes:
      - "${DATA_DIR:-./data}:/app/data"
      - "./chatbot:/app"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    stdin_open: true
    tty: true
    restart: always

  ai-models:
  image: ai-models
  environment:
    - OPENAI_API_KEY=${OPENAI_API_KEY}
  restart: always
